In [ ]:
#generally exploring the data

In [1]:
import pandas as pd 
df = pd.read_csv('311_Service_Requests_20260212.csv')
df.head()

,service_request_id,requested_date,updated_date,closed_date,status_description,source,service_name,agency_responsible,address,comm_code,comm_name,location_type,longitude,latitude,point
0,18-01017964,2018/10/17 12:00:00 AM,2020/06/24 12:00:00 AM,2020/06/24 12:00:00 AM,Closed,Phone,Roads - Traffic Signal Timing Inquiry,TRAN - Roads,NaN,SHN,SHAWNESSY,Community Centrepoint,-114.073757,50.903303,POINT (-114.073756821499 50.903303329478)
1,18-01094780,2018/11/12 12:00:00 AM,2020/06/24 12:00:00 AM,2020/06/24 12:00:00 AM,Closed,App,Roads - Traffic Signal Timing Inquiry,TRAN - Roads,NaN,DAL,DALHOUSIE,Community Centrepoint,-114.158165,51.109414,POINT (-114.158164615208 51.109413833961)
2,21-00609171,2021/08/17 12:00:00 AM,2021/08/19 12:00:00 AM,2021/08/19 12:00:00 AM,Closed,Phone,Bylaw - Noise Concerns,CS - Calgary Community Standards,NaN,BLN,BELTLINE,Community Centrepoint,-114.055189,51.037438,POINT (-114.055188797256 51.037437926217)
3,21-00609175,2021/08/17 12:00:00 AM,2021/08/19 12:00:00 AM,2021/08/19 12:00:00 AM,Closed,Phone,CBS Inspection - Electrical,PD - Calgary Building Services,NaN,HAR,HARVEST HILLS,Community Centrepoint,-114.052778,51.147678,POINT (-114.052777977324 51.14767758603)
4,18-00680955,2018/07/10 12:00:00 AM,2021/02/04 12:00:00 AM,2021/02/04 12:00:00 AM,Closed,Web,Roads - Debris on Street/Sidewalk/Boulevard,TRAN - Roads,NaN,DOV,DOVER,Community Centrepoint,-113.993151,51.022463,POINT (-113.993150510368 51.022462990084)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7164014 entries, 0 to 7164013
Data columns (total 15 columns):
 #   Column              Dtype
---  ------              -----
 0   service_request_id  object
 1   requested_date      object
 2   updated_date        object
 3   closed_date         object
 4   status_description  object
 5   source              object
 6   service_name        object
 7   agency_responsible  object
 8   address             float64
 9   comm_code           object
 10  comm_name           object
 11  location_type       object
 12  longitude           float64
 13  latitude            float64
 14  point               object
dtypes: float64(3), object(12)
memory usage: 819.9+ MB

In [3]:
df.shape

(7164014, 15)

In [4]:
df.dtypes

service_request_id     object
requested_date         object
updated_date           object
closed_date            object
status_description     object
source                 object
service_name           object
agency_responsible     object
address               float64
comm_code              object
comm_name              object
location_type          object
longitude             float64
latitude              float64
point                  object
dtype: object

In [5]:
df.nunique()

service_request_id    7164014
requested_date        3804488
updated_date          3402254
closed_date           3557460
status_description          5
source                      4
service_name             1125
agency_responsible         87
address                     0
comm_code                 322
comm_name                 324
location_type               1
longitude                 921
latitude                 1181
point                    1743
dtype: int64

In [ ]:
#checking for duplicates

In [6]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
7164009    False
7164010    False
7164011    False
7164012    False
7164013    False
Length: 7164014, dtype: bool

In [7]:
sum(df.duplicated())

0

In [ ]:
#changing the data type of date column and deleting the timestamp

In [8]:
df['requested_date'] = pd.to_datetime(df['requested_date'], format='%Y/%m/%d %I:%M:%S %p')
df['requested_date'] = df['requested_date'].dt.date

In [9]:
df['closed_date'] = pd.to_datetime(df['closed_date'], format='%Y/%m/%d %I:%M:%S %p')
df['closed_date'] = df['closed_date'].dt.date

In [ ]:
#dropping unnecessary columns

In [10]:
columns_to_drop = ["service_request_id", "source", "address", "comm_code",
                   "location_type", "point", "updated_date"]
df.drop(columns_to_drop, axis=1, inplace=True)

In [11]:
df.head()

,requested_date,closed_date,status_description,service_name,agency_responsible,comm_name,longitude,latitude
0,2018-10-17,2020-06-24,Closed,Roads - Traffic Signal Timing Inquiry,TRAN - Roads,SHAWNESSY,-114.073757,50.903303
1,2018-11-12,2020-06-24,Closed,Roads - Traffic Signal Timing Inquiry,TRAN - Roads,DALHOUSIE,-114.158165,51.109414
2,2021-08-17,2021-08-19,Closed,Bylaw - Noise Concerns,CS - Calgary Community Standards,BELTLINE,-114.055189,51.037438
3,2021-08-17,2021-08-19,Closed,CBS Inspection - Electrical,PD - Calgary Building Services,HARVEST HILLS,-114.052778,51.147678
4,2018-07-10,2021-02-04,Closed,Roads - Debris on Street/Sidewalk/Boulevard,TRAN - Roads,DOVER,-113.993151,51.022463

In [12]:
df[df['status_description'] == 'TO BE DELETED']

,requested_date,closed_date,status_description,service_name,agency_responsible,comm_name,longitude,latitude
87251,2020-05-07,2020-05-08,TO BE DELETED,Roads - Streetlight Damage,TRAN - Roads,HORIZON,-113.991712,51.089901
288952,2021-02-12,2021-02-12,TO BE DELETED,CT - Bus Stops,TRAN - Calgary Transit,SCENIC ACRES,-114.217258,51.112691
305891,2020-03-29,2020-03-29,TO BE DELETED,Compliance - Business Licence Concern,CS - Calgary Community Standards,HORIZON,-113.991712,51.089901
311312,2020-03-29,2020-03-29,TO BE DELETED,Roads - Signs - Parking,TRAN - Roads,HORIZON,-113.991712,51.089901
311313,2020-03-29,2020-03-29,TO BE DELETED,Roads - Detour Urgent (Safety) Concerns,TRAN - Roads,HORIZON,-113.991712,51.089901
...,...,...,...,...,...,...,...,...
1800233,2021-01-24,2021-01-26,TO BE DELETED,CFD - Fire Code and General Inquiries - FHB,CS - Calgary Fire,DEER RIDGE,-114.020234,50.926574
1803016,2021-01-24,2021-01-24,TO BE DELETED,CFD - Inspection - Provincial Accreditation or...,CS - Calgary Fire,BELTLINE,-114.055189,51.037438
1803017,2021-01-24,2021-01-24,TO BE DELETED,CFD - Inspection - Pre-Purchase Insurance - FHB,CS - Calgary Fire,MOUNT PLEASANT,-114.076028,51.074231
1803018,2021-01-24,2021-01-24,TO BE DELETED,CFD - Inspection - Business Licence - FHB,CS - Calgary Fire,DEER RIDGE,-114.020234,50.926574
1803019,2021-01-24,2021-01-26,TO BE DELETED,CFD - Inspection - Business Licence - FHB,CS - Calgary Fire,DEER RIDGE,-114.020234,50.926574

In [ ]:
#checking and deleting rows that are duplicated and need to be removed

In [13]:
rows_to_drop = df[df['status_description'] == 'TO BE DELETED']
df = df.drop(rows_to_drop.index)

In [14]:
df = df.reset_index(drop=True)

In [15]:
df[df['status_description'] == 'TO BE DELETED']

Empty DataFrame
Columns: [requested_date, closed_date, status_description, service_name, agency_responsible, comm_name, longitude, latitude]
Index: []

In [17]:
df[df['status_description'] == 'Duplicate (Open)']

,requested_date,closed_date,status_description,service_name,agency_responsible,comm_name,longitude,latitude
18212,2021-08-19,NaT,Duplicate (Open),Roads - Pothole Maintenance,TRAN - Roads,SADDLE RIDGE,-113.945623,51.130573
25333,2021-07-12,NaT,Duplicate (Open),Roads - Backlane Maintenance,TRAN - Roads,MONTGOMERY,-114.162276,51.071108
30040,2025-05-31,NaT,Duplicate (Open),Roads - Roadway Maintenance,OS - Mobility,SIGNAL HILL,-114.179907,51.023260
30866,2023-02-10,NaT,Duplicate (Open),Roads - Snow and Ice Control,OS - Mobility,BRIDLEWOOD,-114.110226,50.899257
30940,2023-02-10,NaT,Duplicate (Open),Roads - Snow and Ice Control,OS - Mobility,BRIDLEWOOD,-114.110226,50.899257
...,...,...,...,...,...,...,...,...
7158938,2024-08-26,NaT,Duplicate (Open),Roads - Pothole Maintenance,OS - Mobility,EVERGREEN,-114.115694,50.918704
7162513,2024-06-28,NaT,Duplicate (Open),Roads - Backlane Maintenance,OS - Mobility,BOWNESS,-114.188388,51.083346
7162516,2024-06-28,NaT,Duplicate (Open),Roads - Backlane Maintenance,OS - Mobility,OGDEN,-114.012439,50.991873
7162909,2025-09-05,NaT,Duplicate (Open),Roads - Pothole Maintenance,OS - Mobility,BRENTWOOD,-114.135919,51.096066
7162972,2025-09-05,NaT,Duplicate (Open),Roads - Pothole Maintenance,OS - Mobility,STARFIELD EAST,-113.916653,51.005016

In [18]:
df[df['status_description'] == 'Duplicate (Closed)']

,requested_date,closed_date,status_description,service_name,agency_responsible,comm_name,longitude,latitude
152,2012-07-22,2012-07-22,Duplicate (Closed),Z - Roads - Traffic or Pedestrian Light Repair,TRAN - Roads,WHITEHORN,-113.970068,51.088773
316,2012-07-15,2012-07-17,Duplicate (Closed),Z - Roads - Debris on Backlane/Sidewalk/BV,TRAN - Roads,TEMPLE,-113.946768,51.088795
393,2012-07-19,2012-07-30,Duplicate (Closed),Z - Roads - Backlane Maintenance,TRAN - Roads,KILLARNEY/GLENGARRY,-114.131702,51.030129
480,2012-07-19,2012-07-19,Duplicate (Closed),Z - Roads - Traffic or Pedestrian Light Repair,TRAN - Roads,EAU CLAIRE,-114.072821,51.053607
584,2012-07-20,2012-07-20,Duplicate (Closed),Z - Roads - Dead Animal Pick-Up,TRAN - Roads,CITADEL,-114.183917,51.144536
...,...,...,...,...,...,...,...,...
7163717,2025-08-26,2025-09-05,Duplicate (Closed),Roads - Pothole Maintenance,OS - Mobility,PENBROOKE MEADOWS,-113.947687,51.045853
7163721,2025-08-26,2025-09-05,Duplicate (Closed),Roads - Pothole Maintenance,OS - Mobility,MARLBOROUGH PARK,-113.946703,51.059690
7163730,2025-08-26,2025-09-05,Duplicate (Closed),Roads - Pothole Maintenance,OS - Mobility,MARLBOROUGH PARK,-113.946703,51.059690
7163732,2025-08-26,2025-09-05,Duplicate (Closed),Roads - Pothole Maintenance,OS - Mobility,MARLBOROUGH PARK,-113.946703,51.059690
7163779,2025-08-30,2025-09-05,Duplicate (Closed),Roads - Pothole Maintenance,OS - Mobility,DOVER,-113.993054,51.022568

In [22]:
rows_to_drop = df[df['status_description'] == "Duplicate (Closed)"]
df = df.drop(rows_to_drop.index)

In [23]:
rows_to_drop = df[df['status_description'] == "Duplicate (Open)"]
df = df.drop(rows_to_drop.index)

In [24]:
df[df['status_description'] == 'Duplicate (Open)']

Empty DataFrame
Columns: [requested_date, closed_date, status_description, service_name, agency_responsible, comm_name, longitude, latitude]
Index: []

In [25]:
df[df['status_description'] == 'Duplicate (Closed)']

Empty DataFrame
Columns: [requested_date, closed_date, status_description, service_name, agency_responsible, comm_name, longitude, latitude]
Index: []